blank_issues_enabled: true
contact_links:
  - name: YukiCoin Core Security Policy
    url: https://github.com/YukiCoin/YukiCoin/blob/master/SECURITY.md
    about: View security policy
  - name: YukiCoin Core Developers
    url: https://YukiCoincore.org
    about: YukiCoin Core homepage
